 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BodyMeasurement {
  'id' : string,
  'value' : number,
  'userId' : string,
  'unit' : string,
  'bodyPart' : string,
  'loggedAt' : bigint,
}
export interface BodyWeightEntry {
  'id' : string,
  'weight' : number,
  'userId' : string,
  'unit' : string,
  'loggedAt' : bigint,
}
export interface Exercise {
  'id' : string,
  'name' : string,
  'category' : string,
  'muscleGroup' : string,
}
export interface SessionExercise {
  'id' : string,
  'exerciseId' : string,
  'order' : bigint,
  'sets' : Array<WorkoutSet>,
}
export interface SessionExerciseInput {
  'exerciseId' : string,
  'order' : bigint,
  'sets' : Array<WorkoutSetInput>,
}
export interface TemplateExercise {
  'exerciseId' : string,
  'order' : bigint,
  'sets' : bigint,
}
export interface User {
  'id' : string,
  'username' : string,
  'name' : string,
  'email' : string,
}
export interface WorkoutSession {
  'id' : string,
  'startedAt' : bigint,
  'totalVolume' : number,
  'templateId' : [] | [string],
  'userId' : string,
  'name' : string,
  'exercises' : Array<SessionExercise>,
  'durationSeconds' : [] | [bigint],
  'notes' : [] | [string],
  'prCount' : bigint,
  'finishedAt' : [] | [bigint],
}
export interface WorkoutSet {
  'id' : string,
  'setNumber' : bigint,
  'weight' : [] | [number],
  'isPR' : boolean,
  'reps' : [] | [bigint],
  'completed' : boolean,
}
export interface WorkoutSetInput {
  'setNumber' : bigint,
  'weight' : [] | [number],
  'isPR' : boolean,
  'reps' : [] | [bigint],
  'completed' : boolean,
}
export interface WorkoutTemplate {
  'id' : string,
  'userId' : string,
  'name' : string,
  'createdAt' : bigint,
  'exercises' : Array<TemplateExercise>,
}
export interface _SERVICE {
  'addBodyMeasurement' : ActorMethod<
    [string, string, number, string, bigint],
    BodyMeasurement
  >,
  'addBodyWeightEntry' : ActorMethod<
    [string, number, string, bigint],
    BodyWeightEntry
  >,
  'addExerciseToSession' : ActorMethod<[string, string], WorkoutSession>,
  'createTemplate' : ActorMethod<
    [string, string, Array<TemplateExercise>],
    WorkoutTemplate
  >,
  'createWorkoutSession' : ActorMethod<
    [string, string, [] | [string]],
    WorkoutSession
  >,
  'deleteTemplate' : ActorMethod<[string], boolean>,
  'deleteWorkoutSession' : ActorMethod<[string], boolean>,
  'finishWorkoutSession' : ActorMethod<[string, bigint], WorkoutSession>,
  'getBodyMeasurements' : ActorMethod<
    [string, [] | [string]],
    Array<BodyMeasurement>
  >,
  'getBodyWeightEntries' : ActorMethod<[string], Array<BodyWeightEntry>>,
  'getExerciseList' : ActorMethod<[], Array<Exercise>>,
  'getTemplate' : ActorMethod<[string], WorkoutTemplate>,
  'getTemplates' : ActorMethod<[string], Array<WorkoutTemplate>>,
  'getUser' : ActorMethod<[string], User>,
  'getWorkoutSession' : ActorMethod<[string], WorkoutSession>,
  'getWorkoutSessions' : ActorMethod<[string], Array<WorkoutSession>>,
  'searchExercises' : ActorMethod<[string], Array<Exercise>>,
  'seed' : ActorMethod<[], undefined>,
  'updateUser' : ActorMethod<[string, string, string, string], User>,
  'updateWorkoutSession' : ActorMethod<
    [string, string, [] | [string], [] | [Array<SessionExerciseInput>]],
    WorkoutSession
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];