/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BodyMeasurement = IDL.Record({
  'id' : IDL.Text,
  'value' : IDL.Float64,
  'userId' : IDL.Text,
  'unit' : IDL.Text,
  'bodyPart' : IDL.Text,
  'loggedAt' : IDL.Int,
});
export const BodyWeightEntry = IDL.Record({
  'id' : IDL.Text,
  'weight' : IDL.Float64,
  'userId' : IDL.Text,
  'unit' : IDL.Text,
  'loggedAt' : IDL.Int,
});
export const WorkoutSet = IDL.Record({
  'id' : IDL.Text,
  'setNumber' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Float64),
  'isPR' : IDL.Bool,
  'reps' : IDL.Opt(IDL.Nat),
  'completed' : IDL.Bool,
});
export const SessionExercise = IDL.Record({
  'id' : IDL.Text,
  'exerciseId' : IDL.Text,
  'order' : IDL.Nat,
  'sets' : IDL.Vec(WorkoutSet),
});
export const WorkoutSession = IDL.Record({
  'id' : IDL.Text,
  'startedAt' : IDL.Int,
  'totalVolume' : IDL.Float64,
  'templateId' : IDL.Opt(IDL.Text),
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(SessionExercise),
  'durationSeconds' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Opt(IDL.Text),
  'prCount' : IDL.Nat,
  'finishedAt' : IDL.Opt(IDL.Int),
});
export const Exercise = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isCustom' : IDL.Bool,
  'category' : IDL.Text,
  'muscleGroup' : IDL.Text,
});
export const TemplateExercise = IDL.Record({
  'exerciseId' : IDL.Text,
  'order' : IDL.Nat,
  'sets' : IDL.Nat,
});
export const WorkoutTemplate = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'exercises' : IDL.Vec(TemplateExercise),
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const WorkoutSetInput = IDL.Record({
  'setNumber' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Float64),
  'isPR' : IDL.Bool,
  'reps' : IDL.Opt(IDL.Nat),
  'completed' : IDL.Bool,
});
export const SessionExerciseInput = IDL.Record({
  'exerciseId' : IDL.Text,
  'order' : IDL.Nat,
  'sets' : IDL.Vec(WorkoutSetInput),
});

export const idlService = IDL.Service({
  'addBodyMeasurement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
      [BodyMeasurement],
      [],
    ),
  'addBodyWeightEntry' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
      [BodyWeightEntry],
      [],
    ),
  'addExerciseToSession' : IDL.Func([IDL.Text, IDL.Text], [WorkoutSession], []),
  'createCustomExercise' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Exercise],
      [],
    ),
  'createTemplate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(TemplateExercise)],
      [WorkoutTemplate],
      [],
    ),
  'createWorkoutSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [WorkoutSession],
      [],
    ),
  'deleteTemplate' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteWorkoutSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'finishWorkoutSession' : IDL.Func([IDL.Text, IDL.Int], [WorkoutSession], []),
  'getBodyMeasurements' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(BodyMeasurement)],
      ['query'],
    ),
  'getBodyWeightEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BodyWeightEntry)],
      ['query'],
    ),
  'getExerciseList' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getExercisesByMuscleGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getTemplate' : IDL.Func([IDL.Text], [WorkoutTemplate], ['query']),
  'getTemplates' : IDL.Func([IDL.Text], [IDL.Vec(WorkoutTemplate)], ['query']),
  'getUser' : IDL.Func([IDL.Text], [User], ['query']),
  'getWorkoutSession' : IDL.Func([IDL.Text], [WorkoutSession], ['query']),
  'getWorkoutSessions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkoutSession)],
      ['query'],
    ),
  'searchExercises' : IDL.Func([IDL.Text], [IDL.Vec(Exercise)], ['query']),
  'seed' : IDL.Func([], [], []),
  'updateUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [User], []),
  'updateWorkoutSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(SessionExerciseInput)),
      ],
      [WorkoutSession],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BodyMeasurement = IDL.Record({
    'id' : IDL.Text,
    'value' : IDL.Float64,
    'userId' : IDL.Text,
    'unit' : IDL.Text,
    'bodyPart' : IDL.Text,
    'loggedAt' : IDL.Int,
  });
  const BodyWeightEntry = IDL.Record({
    'id' : IDL.Text,
    'weight' : IDL.Float64,
    'userId' : IDL.Text,
    'unit' : IDL.Text,
    'loggedAt' : IDL.Int,
  });
  const WorkoutSet = IDL.Record({
    'id' : IDL.Text,
    'setNumber' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Float64),
    'isPR' : IDL.Bool,
    'reps' : IDL.Opt(IDL.Nat),
    'completed' : IDL.Bool,
  });
  const SessionExercise = IDL.Record({
    'id' : IDL.Text,
    'exerciseId' : IDL.Text,
    'order' : IDL.Nat,
    'sets' : IDL.Vec(WorkoutSet),
  });
  const WorkoutSession = IDL.Record({
    'id' : IDL.Text,
    'startedAt' : IDL.Int,
    'totalVolume' : IDL.Float64,
    'templateId' : IDL.Opt(IDL.Text),
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(SessionExercise),
    'durationSeconds' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Opt(IDL.Text),
    'prCount' : IDL.Nat,
    'finishedAt' : IDL.Opt(IDL.Int),
  });
  const Exercise = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isCustom' : IDL.Bool,
    'category' : IDL.Text,
    'muscleGroup' : IDL.Text,
  });
  const TemplateExercise = IDL.Record({
    'exerciseId' : IDL.Text,
    'order' : IDL.Nat,
    'sets' : IDL.Nat,
  });
  const WorkoutTemplate = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'exercises' : IDL.Vec(TemplateExercise),
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const WorkoutSetInput = IDL.Record({
    'setNumber' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Float64),
    'isPR' : IDL.Bool,
    'reps' : IDL.Opt(IDL.Nat),
    'completed' : IDL.Bool,
  });
  const SessionExerciseInput = IDL.Record({
    'exerciseId' : IDL.Text,
    'order' : IDL.Nat,
    'sets' : IDL.Vec(WorkoutSetInput),
  });
  
  return IDL.Service({
    'addBodyMeasurement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
        [BodyMeasurement],
        [],
      ),
    'addBodyWeightEntry' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
        [BodyWeightEntry],
        [],
      ),
    'addExerciseToSession' : IDL.Func(
        [IDL.Text, IDL.Text],
        [WorkoutSession],
        [],
      ),
    'createCustomExercise' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Exercise],
        [],
      ),
    'createTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(TemplateExercise)],
        [WorkoutTemplate],
        [],
      ),
    'createWorkoutSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [WorkoutSession],
        [],
      ),
    'deleteTemplate' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteWorkoutSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'finishWorkoutSession' : IDL.Func(
        [IDL.Text, IDL.Int],
        [WorkoutSession],
        [],
      ),
    'getBodyMeasurements' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(BodyMeasurement)],
        ['query'],
      ),
    'getBodyWeightEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BodyWeightEntry)],
        ['query'],
      ),
    'getExerciseList' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getExercisesByMuscleGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getTemplate' : IDL.Func([IDL.Text], [WorkoutTemplate], ['query']),
    'getTemplates' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkoutTemplate)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Text], [User], ['query']),
    'getWorkoutSession' : IDL.Func([IDL.Text], [WorkoutSession], ['query']),
    'getWorkoutSessions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'searchExercises' : IDL.Func([IDL.Text], [IDL.Vec(Exercise)], ['query']),
    'seed' : IDL.Func([], [], []),
    'updateUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [User],
        [],
      ),
    'updateWorkoutSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(SessionExerciseInput)),
        ],
        [WorkoutSession],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };