/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    id: string;
    name: string;
    category: string;
    muscleGroup: string;
}
export interface TemplateExercise {
    exerciseId: string;
    order: bigint;
    sets: bigint;
}
export interface BodyMeasurement {
    id: string;
    value: number;
    userId: string;
    unit: string;
    bodyPart: string;
    loggedAt: bigint;
}
export interface WorkoutSet {
    id: string;
    setNumber: bigint;
    weight?: number;
    isPR: boolean;
    reps?: bigint;
    completed: boolean;
}
export interface WorkoutSession {
    id: string;
    startedAt: bigint;
    totalVolume: number;
    templateId?: string;
    userId: string;
    name: string;
    exercises: Array<SessionExercise>;
    durationSeconds?: bigint;
    notes?: string;
    prCount: bigint;
    finishedAt?: bigint;
}
export interface SessionExerciseInput {
    exerciseId: string;
    order: bigint;
    sets: Array<WorkoutSetInput>;
}
export interface User {
    id: string;
    username: string;
    name: string;
    email: string;
}
export interface BodyWeightEntry {
    id: string;
    weight: number;
    userId: string;
    unit: string;
    loggedAt: bigint;
}
export interface WorkoutSetInput {
    setNumber: bigint;
    weight?: number;
    isPR: boolean;
    reps?: bigint;
    completed: boolean;
}
export interface WorkoutTemplate {
    id: string;
    userId: string;
    name: string;
    createdAt: bigint;
    exercises: Array<TemplateExercise>;
}
export interface SessionExercise {
    id: string;
    exerciseId: string;
    order: bigint;
    sets: Array<WorkoutSet>;
}
export interface backendInterface {
    addBodyMeasurement(userId: string, bodyPart: string, value: number, unit: string, loggedAt: bigint): Promise<BodyMeasurement>;
    addBodyWeightEntry(userId: string, weight: number, unit: string, loggedAt: bigint): Promise<BodyWeightEntry>;
    addExerciseToSession(sessionId: string, exerciseId: string): Promise<WorkoutSession>;
    createTemplate(userId: string, name: string, exercises: Array<TemplateExercise>): Promise<WorkoutTemplate>;
    createWorkoutSession(userId: string, name: string, templateId: string | null): Promise<WorkoutSession>;
    deleteTemplate(id: string): Promise<boolean>;
    deleteWorkoutSession(id: string): Promise<boolean>;
    finishWorkoutSession(id: string, finishedAt: bigint): Promise<WorkoutSession>;
    getBodyMeasurements(userId: string, bodyPart: string | null): Promise<Array<BodyMeasurement>>;
    getBodyWeightEntries(userId: string): Promise<Array<BodyWeightEntry>>;
    getExerciseList(): Promise<Array<Exercise>>;
    getTemplate(id: string): Promise<WorkoutTemplate>;
    getTemplates(userId: string): Promise<Array<WorkoutTemplate>>;
    getUser(id: string): Promise<User>;
    getWorkoutSession(id: string): Promise<WorkoutSession>;
    getWorkoutSessions(userId: string): Promise<Array<WorkoutSession>>;
    searchExercises(searchQuery: string): Promise<Array<Exercise>>;
    seed(): Promise<void>;
    updateUser(id: string, name: string, username: string, email: string): Promise<User>;
    updateWorkoutSession(id: string, name: string, notes: string | null, exercisesInput: Array<SessionExerciseInput> | null): Promise<WorkoutSession>;
}
import type { SessionExercise as _SessionExercise, SessionExerciseInput as _SessionExerciseInput, WorkoutSession as _WorkoutSession, WorkoutSet as _WorkoutSet, WorkoutSetInput as _WorkoutSetInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBodyMeasurement(arg0: string, arg1: string, arg2: number, arg3: string, arg4: bigint): Promise<BodyMeasurement> {
        if (this.processError) {
            try {
                const result = await this.actor.addBodyMeasurement(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBodyMeasurement(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addBodyWeightEntry(arg0: string, arg1: number, arg2: string, arg3: bigint): Promise<BodyWeightEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addBodyWeightEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBodyWeightEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addExerciseToSession(arg0: string, arg1: string): Promise<WorkoutSession> {
        if (this.processError) {
            try {
                const result = await this.actor.addExerciseToSession(arg0, arg1);
                return from_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExerciseToSession(arg0, arg1);
            return from_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTemplate(arg0: string, arg1: string, arg2: Array<TemplateExercise>): Promise<WorkoutTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.createTemplate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTemplate(arg0, arg1, arg2);
            return result;
        }
    }
    async createWorkoutSession(arg0: string, arg1: string, arg2: string | null): Promise<WorkoutSession> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkoutSession(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
                return from_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkoutSession(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
            return from_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTemplate(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemplate(arg0);
            return result;
        }
    }
    async deleteWorkoutSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkoutSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkoutSession(arg0);
            return result;
        }
    }
    async finishWorkoutSession(arg0: string, arg1: bigint): Promise<WorkoutSession> {
        if (this.processError) {
            try {
                const result = await this.actor.finishWorkoutSession(arg0, arg1);
                return from_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finishWorkoutSession(arg0, arg1);
            return from_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBodyMeasurements(arg0: string, arg1: string | null): Promise<Array<BodyMeasurement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBodyMeasurements(arg0, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBodyMeasurements(arg0, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getBodyWeightEntries(arg0: string): Promise<Array<BodyWeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBodyWeightEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBodyWeightEntries(arg0);
            return result;
        }
    }
    async getExerciseList(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExerciseList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExerciseList();
            return result;
        }
    }
    async getTemplate(arg0: string): Promise<WorkoutTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplate(arg0);
            return result;
        }
    }
    async getTemplates(arg0: string): Promise<Array<WorkoutTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplates(arg0);
            return result;
        }
    }
    async getUser(arg0: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return result;
        }
    }
    async getWorkoutSession(arg0: string): Promise<WorkoutSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutSession(arg0);
                return from_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutSession(arg0);
            return from_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutSessions(arg0: string): Promise<Array<WorkoutSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutSessions(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutSessions(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchExercises(arg0: string): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchExercises(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchExercises(arg0);
            return result;
        }
    }
    async seed(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seed();
            return result;
        }
    }
    async updateUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateWorkoutSession(arg0: string, arg1: string, arg2: string | null, arg3: Array<SessionExerciseInput> | null): Promise<WorkoutSession> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkoutSession(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
                return from_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkoutSession(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
            return from_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_SessionExercise_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionExercise): SessionExercise {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutSession_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutSession): WorkoutSession {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutSet_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutSet): WorkoutSet {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startedAt: bigint;
    totalVolume: number;
    templateId: [] | [string];
    userId: string;
    name: string;
    exercises: Array<_SessionExercise>;
    durationSeconds: [] | [bigint];
    notes: [] | [string];
    prCount: bigint;
    finishedAt: [] | [bigint];
}): {
    id: string;
    startedAt: bigint;
    totalVolume: number;
    templateId?: string;
    userId: string;
    name: string;
    exercises: Array<SessionExercise>;
    durationSeconds?: bigint;
    notes?: string;
    prCount: bigint;
    finishedAt?: bigint;
} {
    return {
        id: value.id,
        startedAt: value.startedAt,
        totalVolume: value.totalVolume,
        templateId: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.templateId)),
        userId: value.userId,
        name: value.name,
        exercises: from_candid_vec_n4(_uploadFile, _downloadFile, value.exercises),
        durationSeconds: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.durationSeconds)),
        notes: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.notes)),
        prCount: value.prCount,
        finishedAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.finishedAt))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    exerciseId: string;
    order: bigint;
    sets: Array<_WorkoutSet>;
}): {
    id: string;
    exerciseId: string;
    order: bigint;
    sets: Array<WorkoutSet>;
} {
    return {
        id: value.id,
        exerciseId: value.exerciseId,
        order: value.order,
        sets: from_candid_vec_n7(_uploadFile, _downloadFile, value.sets)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    setNumber: bigint;
    weight: [] | [number];
    isPR: boolean;
    reps: [] | [bigint];
    completed: boolean;
}): {
    id: string;
    setNumber: bigint;
    weight?: number;
    isPR: boolean;
    reps?: bigint;
    completed: boolean;
} {
    return {
        id: value.id,
        setNumber: value.setNumber,
        weight: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.weight)),
        isPR: value.isPR,
        reps: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.reps)),
        completed: value.completed
    };
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutSession>): Array<WorkoutSession> {
    return value.map((x)=>from_candid_WorkoutSession_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SessionExercise>): Array<SessionExercise> {
    return value.map((x)=>from_candid_SessionExercise_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutSet>): Array<WorkoutSet> {
    return value.map((x)=>from_candid_WorkoutSet_n8(_uploadFile, _downloadFile, x));
}
function to_candid_SessionExerciseInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionExerciseInput): _SessionExerciseInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutSetInput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutSetInput): _WorkoutSetInput {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SessionExerciseInput> | null): [] | [Array<_SessionExerciseInput>] {
    return value === null ? candid_none() : candid_some(to_candid_vec_n16(_uploadFile, _downloadFile, value));
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exerciseId: string;
    order: bigint;
    sets: Array<WorkoutSetInput>;
}): {
    exerciseId: string;
    order: bigint;
    sets: Array<_WorkoutSetInput>;
} {
    return {
        exerciseId: value.exerciseId,
        order: value.order,
        sets: to_candid_vec_n19(_uploadFile, _downloadFile, value.sets)
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    setNumber: bigint;
    weight?: number;
    isPR: boolean;
    reps?: bigint;
    completed: boolean;
}): {
    setNumber: bigint;
    weight: [] | [number];
    isPR: boolean;
    reps: [] | [bigint];
    completed: boolean;
} {
    return {
        setNumber: value.setNumber,
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        isPR: value.isPR,
        reps: value.reps ? candid_some(value.reps) : candid_none(),
        completed: value.completed
    };
}
function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SessionExerciseInput>): Array<_SessionExerciseInput> {
    return value.map((x)=>to_candid_SessionExerciseInput_n17(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<WorkoutSetInput>): Array<_WorkoutSetInput> {
    return value.map((x)=>to_candid_WorkoutSetInput_n20(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
